#!/bin/sh

EPM_VERSION="0.1"

EPM=$(basename $0)
EPM_DIRECTORY=$(dirname $0)

EMACS=${EMACS:-emacs}

usage () {
    cat <<EOF
$EPM - Emacs Package Manager

Usage:
    $EPM <command>
    $EPM [option]

Commands:
    list                List installed packages
    install             Install a package
    delete              Delete a package
    refresh             Download package archives
    info                Display information about a package
    search              Search packages

Options:
    -h, --help          Display this message
    -v, --version       Print version info and exit
EOF
}

list () {
    $EMACS -Q --batch -l $EPM_DIRECTORY/epm.el -f epm-list
}

install () {
    $EMACS -Q --batch -l $EPM_DIRECTORY/epm.el --eval "(epm-install \"$1\")"
}

delete () {
    $EMACS -Q --batch -l $EPM_DIRECTORY/epm.el --eval "(epm-delete \"$1\")"
}

refresh () {
    $EMACS -Q --batch -l $EPM_DIRECTORY/epm.el -f package-refresh-contents
}

info () {
    $EMACS -Q --batch -l $EPM_DIRECTORY/epm.el --eval "(epm-info \"$1\")"
}

search () {
    $EMACS -Q --batch -l $EPM_DIRECTORY/epm.el --eval "(epm-search \"$1\")"
}

# TODO outdated
# TODO upgrade

COMMAND=$1
case $COMMAND in
    "" | "-h" | "--help")
        usage
        ;;
    "-v" | "--version")
        printf "epm %s\n" $EPM_VERSION
        ;;
    "list" | "install" | "delete" | "refresh" | "info" | "search")
        shift
        ${COMMAND} $@
        ;;
    *)
        echo "Error: Unknown command: ${COMMAND}"
        exit 1
        ;;
esac
