#!/bin/sh

EPM_VERSION="0.1"

EPM=$(basename $0)
EPM_DIRECTORY=$(dirname $0)

usage () {
    echo ""
    echo "$EPM - Emacs Package Manager"
    echo ""
    echo "Usage:"
    echo "    $EPM <command>"
    echo "    $EPM [option]"
    echo ""
    echo "Commands:"
    echo "    list                List installed packages"
    echo "    install             Install a package"
    echo "    delete              Delete a package"
    echo ""
    echo "Options:"
    echo "    -h, --help          Display this message"
    echo "    -v, --version       Print version info and exit"
    echo ""
}

list () {
    emacs -Q --batch -l $EPM_DIRECTORY/epm.el -f epm-list
}

install () {
    emacs -Q --batch -l $EPM_DIRECTORY/epm.el --eval "(epm-install \"$1\")"
}

delete () {
    emacs -Q --batch -l $EPM_DIRECTORY/epm.el --eval "(epm-delete \"$1\")"
}

# TODO info
# TODO outdated
# TODO upgrade

COMMAND=$1
case $COMMAND in
    "" | "-h" | "--help")
        usage
        ;;
    "-v" | "--version")
        printf "epm %s\n" $EPM_VERSION
        ;;
    *)
        shift
        ${COMMAND} $@
        ;;
esac
